### ISSUE TITLE
Implement Testing Scenario as python notebooks

### ISSUE THREAD

**Issue by ir4y** [beda-software/au-core-aidbox#2]
https://confluence.hl7.org/display/HA/AU+Core+Track+-+2023-11

**Comment by ir4y** [comment]
https://confluence.hl7.org/pages/viewpage.action?pageId=203358353#Read&SearchTestScenarios-1Patient

https://confluence.hl7.org/pages/viewpage.action?pageId=204276132#Validate&CreateTestScenarios-2.Condition

**Comment by ir4y** [comment]
Find a solution to quickly run notebook in some cloud environment.

**Comment by projkov** [comment]
I think we can use https://mybinder.org/ to share and run notebooks. Let's discuss it tomorrow.

**Comment by projkov** [comment]
I think we can mark this issue as closed. 
Two notebooks are available in the repo and binder
