### ISSUE TITLE
Prepare a data bundle with demo data

### ISSUE THREAD

**Issue by ir4y** [beda-software/au-core-aidbox#4]
It should contain patients with some medical data to test scenarios from https://confluence.hl7.org/display/HA/AU+Core+Track+-+2023-11

https://docs.aidbox.app/api-1/bulk-api-1/synthea-by-bulk-api#load-by-resource-type

Serve ndjson file from https://au-core.beda.software/assets/data.ndjson.gz

Also load it via aidbox seeds

**Comment by ir4y** [comment]
Load it via aidbox seeds

**Comment by projkov** [comment]
Done
